spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  #热部署配置
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
  #数据库连接池
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/elm_db?characterEncoding=utf-8
    username: #####
    password: #######

server:
  servlet:
    context-path: /elm
    jsp:
      init-parameters:
        development: true

    multipart: #运行服务器可以处理的最大文件大小
      max-file-size: 100MB
      max-request-size: 120MB #运行请求传递文件的大小最大值为10MB max-file-size: 120MB
  port: 8988 #?????

  #servlet:
  #context-path: /springboot_day1 #修改项目名 注意:项目名必须 "/" 开头

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.boot.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


logging:
  level:
    springframework: error
  file:
    path: D:\Spring-Vue-Blog\boot-maven\src\main\webapp\images

